[package]
name = "smtprelay"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { version = "0.11.1", features = ["resolv", "resolv-sync"] }
maildb = {path = "../maildb"}
smtp = {path = "../smtp"}
